<a href="https://colab.research.google.com/github/SaidTheCoder/p140/blob/main/p138_140.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (5.0.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.5.30)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [3]:
from google.colab import files
uploaded=files.upload()

Saving kaggle.json to kaggle.json

In [4]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [5]:
!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

Downloading articles-sharing-reading-from-cit-deskdrop.zip to /content
 61% 5.00M/8.20M [00:00<00:00, 27.1MB/s]
100% 8.20M/8.20M [00:00<00:00, 38.9MB/s]

In [6]:
!ls

articles-sharing-reading-from-cit-deskdrop.zip	kaggle.json  sample_data

In [7]:
!unzip articles-sharing-reading-from-cit-deskdrop.zip

Archive:  articles-sharing-reading-from-cit-deskdrop.zip
  inflating: shared_articles.csv
  inflating: users_interactions.csv

In [8]:
!ls

articles-sharing-reading-from-cit-deskdrop.zip	shared_articles.csv
kaggle.json					users_interactions.csv
sample_data

In [9]:
import pandas as pd
df1=pd.read_csv("shared_articles.csv")
df1.head()

    timestamp  ... lang
0  1459192779  ...   en
1  1459193988  ...   en
2  1459194146  ...   en
3  1459194474  ...   en
4  1459194497  ...   en

[5 rows x 13 columns]

In [10]:
df2=pd.read_csv("users_interactions.csv")
df2.head(60)

     timestamp eventType  ...  userRegion  userCountry
0   1465413032      VIEW  ...         NaN          NaN
1   1465412560      VIEW  ...          NY           US
2   1465416190      VIEW  ...         NaN          NaN
3   1465413895    FOLLOW  ...         NaN          NaN
4   1465412290      VIEW  ...         NaN          NaN
5   1465413742      VIEW  ...          MG           BR
6   1465415950      VIEW  ...         NaN          NaN
7   1465415066      VIEW  ...          SP           BR
8   1465413762      VIEW  ...         NaN          NaN
9   1465413771      VIEW  ...         NaN          NaN
10  1465413864      VIEW  ...         NaN          NaN
11  1465415229      VIEW  ...         NaN          NaN
12  1465415228      VIEW  ...          SP           BR
13  1465415691      VIEW  ...          SP           BR
14  1465413171      VIEW  ...         NaN          NaN
15  1465415259      VIEW  ...          SP           BR
16  1465415623      VIEW  ...          SP           BR
17  1465412288      VIEW  ...          MG           BR
18  1465415693      VIEW  ...          MG           BR
19  1465415691      VIEW  ...         NaN          NaN
20  1465416196      VIEW  ...          SP           BR
21  1465415431      VIEW  ...          SP           BR
22  1465415060      VIEW  ...         NaN          NaN
23  1465413743      VIEW  ...         NaN          NaN
24  1465415565      VIEW  ...          SP           BR
25  1465413879  BOOKMARK  ...         NaN          NaN
26  1465415695      VIEW  ...         NaN          NaN
27  1465413954  BOOKMARK  ...         NaN          NaN
28  1465413735      VIEW  ...          SP           BR
29  1465414324      VIEW  ...          SP           BR
30  1465413771      VIEW  ...          SP           BR
31  1465413781      VIEW  ...          SP           BR
32  1465413864      VIEW  ...          SP           BR
33  1465415756      LIKE  ...         NaN          NaN
34  1465413046      VIEW  ...          SP           BR
35  1465415686      VIEW  ...         NaN          NaN
36  1465413867      LIKE  ...         NaN          NaN
37  1465413873  BOOKMARK  ...         NaN          NaN
38  1465415690      VIEW  ...          SP           BR
39  1465415949      VIEW  ...          SP           BR
40  1465413845      LIKE  ...         NaN          NaN
41  1465413689      VIEW  ...         NaN          NaN
42  1465413735      VIEW  ...         NaN          NaN
43  1465413946      LIKE  ...         NaN          NaN
44  1465414478      VIEW  ...         NaN          NaN
45  1465413752      VIEW  ...         NaN          NaN
46  1465414324      VIEW  ...         NaN          NaN
47  1465415574      VIEW  ...         NaN          NaN
48  1465414493      VIEW  ...          RJ           BR
49  1465413751      VIEW  ...          SP           BR
50  1465413689      VIEW  ...          SP           BR
51  1465413781      VIEW  ...         NaN          NaN
52  1465413762      VIEW  ...          MG           BR
53  1465412561      VIEW  ...         NaN          NaN
54  1465413171      VIEW  ...          SP           BR
55  1465415430      VIEW  ...         NaN          NaN
56  1465413763      LIKE  ...         NaN          NaN
57  1466034854      VIEW  ...          SP           BR
58  1466034403      VIEW  ...          SP           BR
59  1466033932      VIEW  ...          SP           BR

[60 rows x 8 columns]

In [11]:
df1=df1[df1["eventType"]=="CONTENT SHARED"]
df1.head(10)

     timestamp  ... lang
1   1459193988  ...   en
2   1459194146  ...   en
3   1459194474  ...   en
4   1459194497  ...   en
5   1459194522  ...   en
6   1459194557  ...   en
7   1459194599  ...   en
8   1459194751  ...   en
9   1459194842  ...   en
10  1459210504  ...   pt

[10 rows x 13 columns]

In [12]:
def total_events(df1_row):
  total_likes = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "LIKE")].shape[0]
  total_views = df2[(df2["contentId"] == df1_row["contentId"]) & (df2["eventType"] == "VIEW")].shape[0]
  total_bookmarks = df2[(df2["contentId"]==df1_row["contentId"]) & (df2["eventType"]=="BOOKMARK")].shape[0]
  total_follows = df2[(df2["contentId"]==df1_row["contentId"]) & (df2["eventType"]=="FOLLOW")].shape[0]
  total_comments = df2[(df2["contentId"]==df1_row["contentId"]) & (df2["eventType"]=="COMMENT CREATED")].shape[0]
  return total_likes+total_views+ total_bookmarks+ total_follows+ total_comments
df1["total_events"]=df1.apply(total_events,axis=1)
df1.head(10)

     timestamp       eventType  ...  lang  total_events
1   1459193988  CONTENT SHARED  ...    en             1
2   1459194146  CONTENT SHARED  ...    en             1
3   1459194474  CONTENT SHARED  ...    en            13
4   1459194497  CONTENT SHARED  ...    en             0
5   1459194522  CONTENT SHARED  ...    en             2
6   1459194557  CONTENT SHARED  ...    en             0
7   1459194599  CONTENT SHARED  ...    en             1
8   1459194751  CONTENT SHARED  ...    en             2
9   1459194842  CONTENT SHARED  ...    en            15
10  1459210504  CONTENT SHARED  ...    pt             5

[10 rows x 14 columns]

In [13]:
df1=df1.sort_values("total_events",ascending=False)
df1.head()

       timestamp       eventType  ...  lang  total_events
3096  1487246811  CONTENT SHARED  ...    en           433
1671  1467813728  CONTENT SHARED  ...    pt           315
1814  1468867647  CONTENT SHARED  ...    pt           294
1317  1465484901  CONTENT SHARED  ...    en           294
588   1461629452  CONTENT SHARED  ...    pt           281

[5 rows x 14 columns]

In [14]:
#p140
def clean_data(x):
  if isinstance(x,str):
    return x.lower()
  else:
    return ""
df1["title"]=df1["title"].apply(clean_data)
df1.head()

       timestamp       eventType  ...  lang  total_events
3096  1487246811  CONTENT SHARED  ...    en           433
1671  1467813728  CONTENT SHARED  ...    pt           315
1814  1468867647  CONTENT SHARED  ...    pt           294
1317  1465484901  CONTENT SHARED  ...    en           294
588   1461629452  CONTENT SHARED  ...    pt           281

[5 rows x 14 columns]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer(stop_words="english")
count_matrix=count.fit_transform(df1["title"])
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2=cosine_similarity(count_matrix,count_matrix)
df1=df1.reset_index()
indices=pd.Series(df1.index,index=df1["contentId"])

In [16]:
def get_recomendations(contentId,cosine_sim):
  idx=indices[contentId]
  sim_scores=list(enumerate(cosine_sim[idx]))
  sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)
  sim_scores=sim_scores[1:11]
  movie_indices=[i[0]for i in sim_scores]
  return df1["contentId"].iloc[movie_indices]

In [17]:
get_recomendations(-4029704725707465084,cosine_sim2)

817      174707786647990372
698     5087084654882097891
86      5338677278233757627
181     7088167897470452815
209     4118743389464105405
1109    4625350031392752392
1284   -5679427141235752819
1862     -39485845307123560
2632    8298709454703868984
319    -6245566021053602636
Name: contentId, dtype: int64